# prezto
[[ -s ~/src/git/dotfiles/config/prezto/zshrc ]] && source ~/src/git/dotfiles/config/prezto/zshrc

# Customize Function
[[ -s ~/.zshrc.functions ]] && source ~/.zshrc.functions

# Customize Alias
[[ -s ~/.zshrc.alias ]] && source ~/.zshrc.alias
[[ -s ~/.zshrc.alias.local ]] && source ~/.zshrc.alias.local


# enhancd
[[ -s ~/src/git/enhancd/init.sh ]] && source ~/src/git/enhancd/init.sh; ENHANCD_HOOK_AFTER_CD=ll

# colorditt
[[ -x `which colordiff` ]] && alias diff='colordiff -u'

# zshrc setting
## 補完
autoload -U compinit && compinit -u

## 履歴ファイルの保存先
export HISTFILE=${HOME}/.zsh_history

## メモリに保存される履歴の件数
export HISTSIZE=1000

## 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000

## 重複を記録しない
setopt hist_ignore_dups

## 開始と終了を記録
setopt EXTENDED_HISTORY

## ヒストリに追加されるコマンド行が古いものと同じなら古いものを削除
setopt hist_ignore_all_dups

## historyコマンドは履歴に登録しない
setopt hist_no_store

# keybind
## peco-history
zle -N peco-history
bindkey '^x^h' peco-history

## set-cz-issues
autoload -Uz add-zsh-hook
add-zsh-hook preexec set-cz-issues

# PATH
## TODO: 見直したほうがいいのでコメント
# export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/src/go
export GOBIN=$GOPATH/bin
export PATH="$(brew --prefix)/bin:$PATH";
export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=/usr/local/share/git-core/contrib/diff-highlight:$PATH
export PATH=~/bin:$PATH
export PATH=~/bin/node-bin:$PATH
export PSQL_EDITOR=vi

# pipenvの.venvのプロジェクト直下に作る
export PIPENV_VENV_IN_PROJECT=true

# npm install でコケるので
export NODE_EXTRA_CA_CERTS=/usr/local/etc/openssl/cert.pem

# direnv
type direnv > /dev/null 2>&1 && eval "$(direnv hook zsh)"
